# Generated by Django 5.1.1 on 2024-10-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated_on"]},
        ),
    ]
